SELECT  CITIES.NAME, SUM(RIDES.FARE) AS FARE
FROM    CITIES  JOIN USERS ON CITIES.ID = USERS.CITY_ID
                JOIN RIDES ON USERS.ID = RIDES.USER_ID
GROUP BY    CITIES.NAME
ORDER BY    FARE,
            CITIES.NAME;
